In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [214]:
print(train[1])

[  5.   1.   3.   5.   5.   5.   2.   2.   5.   4.   2.   3.   4.   5.
   1.   1.   1.   1.   1.   5.   5.   4.   5.   4.   3.   1.   5.   5.
   2.   1.   2.   4.   5.   1.   1.   2.   4.   5.   3.   2.   2.   4.
   1.   5.   3.   1.   4.   5.   5.   5.   4.   5.   4.   3.   5.   2.
   1.   3.   3.   5.   5.   3.   5.   2.   2.   4.   1.   1.   2.   4.
   5.   3.   1.   2.   2.   3.   1.   4.   5.   5.   5.   5.   5.   5.
   4.   5.   5.   1.   3.   3.   5.   5.   5.   3.   5.   4.   5.   5.
   5.   1.   2.   4.   4.   5.   5.   1.   5.   1.   4.   2.   4.   4.
   2.   5.   1.   2.   5.   5.   2.   4.   3.   1.   5.   5.   5.   3.
   3.   2.   2.   5.   3.   5.   2.   4.   5.   1.   1.   1.   1.   5.
  19. 166.  58.   1.   1.   2.   4.   1.   2.   1.]


In [216]:
with open('responses.de','a') as f3:
    for i in dev:
        for j in range(len(i)):
            f3.write(str(i[j]))
            if not (len(i)-1 == j):
                f3.write(",")
        f3.write("\n")

In [217]:
with open('responses.te','a') as f3:
    for i in test:
        for j in range(len(i)):
            f3.write(str(i[j]))
            if not (len(i)-1 == j):
                f3.write(",")
        f3.write("\n")

In [2]:
train_data = np.genfromtxt('data/responses.tr', delimiter=",", usecols=np.arange(0,150))
print(train_data)
print(len(train_data))

[[5. 3. 2. ... 1. 1. 1.]
 [5. 1. 3. ... 1. 2. 1.]
 [5. 5. 2. ... 2. 1. 2.]
 ...
 [5. 3. 3. ... 1. 2. 1.]
 [5. 3. 4. ... 1. 1. 2.]
 [5. 2. 2. ... 1. 1. 2.]]
701


In [3]:
Y = train_data[:,99]
X = np.delete(train_data, np.s_[99:100], axis=1)
print(X)
print(Y)

[[5. 3. 2. ... 1. 1. 1.]
 [5. 1. 3. ... 1. 2. 1.]
 [5. 5. 2. ... 2. 1. 2.]
 ...
 [5. 3. 3. ... 1. 2. 1.]
 [5. 3. 4. ... 1. 1. 2.]
 [5. 2. 2. ... 1. 1. 2.]]
[3. 1. 3. 2. 4. 1. 3. 2. 4. 4. 1. 1. 2. 4. 3. 5. 3. 1. 3. 3. 3. 5. 2. 3.
 1. 5. 4. 2. 3. 2. 2. 3. 2. 3. 2. 2. 2. 3. 5. 3. 2. 4. 3. 2. 3. 1. 4. 5.
 3. 1. 5. 3. 2. 3. 4. 4. 5. 3. 3. 3. 2. 3. 1. 4. 2. 5. 3. 4. 2. 3. 3. 3.
 4. 2. 3. 3. 1. 4. 3. 4. 3. 3. 1. 2. 4. 1. 2. 1. 3. 4. 2. 5. 5. 4. 3. 3.
 3. 3. 3. 1. 5. 2. 3. 1. 3. 1. 2. 3. 5. 2. 2. 3. 4. 2. 2. 3. 2. 3. 3. 3.
 2. 2. 3. 3. 2. 3. 4. 4. 1. 4. 3. 2. 3. 4. 4. 3. 2. 2. 5. 3. 5. 4. 2. 5.
 3. 3. 5. 1. 4. 3. 3. 5. 3. 3. 1. 4. 1. 1. 3. 2. 4. 2. 4. 3. 2. 3. 2. 4.
 4. 3. 4. 3. 3. 5. 5. 4. 3. 3. 3. 2. 1. 3. 3. 2. 2. 1. 5. 2. 3. 4. 2. 4.
 3. 2. 3. 1. 3. 3. 4. 1. 3. 2. 2. 2. 4. 5. 5. 2. 5. 2. 4. 2. 3. 5. 2. 2.
 2. 3. 3. 3. 4. 2. 3. 2. 2. 3. 3. 4. 4. 2. 3. 1. 4. 2. 2. 2. 3. 3. 3. 4.
 1. 3. 2. 3. 2. 3. 4. 3. 3. 3. 4. 3. 2. 3. 2. 3. 2. 4. 3. 3. 3. 4. 3. 2.
 2. 1. 4. 5. 2. 5. 2. 4. 4. 5. 4. 2. 5. 2

In [4]:
from baselines import *
dumbclass = most_frequent()
dumbclass.train(X,Y)

196
505


In [235]:
file = []
with open('young-people-survey/responses.csv', "r") as f:
    for x in f:
        file.append(x)

In [201]:
# print(file[0])
split_d = file[0].split(",")
for i in range(len(split_d)):
    if split_d[i] == '"Empathy"':
        print(i)

99
