In [12]:
from preprocessing import *
process_data()

opening file...
data stored...
converting categorical data...
data converted...
new file "formatted_responses.csv" created
splitting data into train/dev/test files
creating responses.tr...
file created...
creating responses.de...
file created...
creating responses.te...
file created...
data split completed...


In [4]:
from preprocessing import *
from numpy import *
import seaborn as sns
Xtr, Ytr = feature_label_split("data/responses.tr")
Xde, Yde = feature_label_split("data/responses.de")
Xte, Yte = feature_label_split("data/responses.te")
print(Xtr)
print(Xde)
print(Xte)

getting Y labels from...
preprocessing Y labels...
done.
getting Y labels from...
preprocessing Y labels...
done.
getting Y labels from...
preprocessing Y labels...
done.
[[5. 3. 2. ... 1. 2. 2.]
 [4. 4. 2. ... 1. 1. 2.]
 [5. 5. 2. ... 1. 1. 2.]
 ...
 [5. 5. 5. ... 2. 1. 2.]
 [5. 3. 4. ... 1. 1. 2.]
 [5. 3. 3. ... 1. 2. 1.]]
[[5. 2. 3. ... 1. 1. 1.]
 [5. 3. 4. ... 1. 1. 2.]
 [5. 4. 2. ... 2. 1. 2.]
 ...
 [4. 3. 1. ... 2. 1. 2.]
 [5. 3. 3. ... 1. 1. 2.]
 [5. 5. 4. ... 1. 2. 1.]]
[[5. 5. 5. ... 1. 1. 2.]
 [5. 2. 1. ... 1. 1. 2.]
 [4. 3. 3. ... 1. 1. 2.]
 ...
 [5. 3. 4. ... 1. 1. 2.]
 [5. 3. 5. ... 1. 1. 2.]
 [5. 4. 4. ... 1. 1. 2.]]


In [3]:
from pylab import *
from baselines import *
import numpy as np

# baseline classifier
# most_frequent class
base = most_frequent()
base.train(Xtr, Ytr)
s3 = base.predict_all(Xde)

print(mean(s3==Yde))

0.6666666666666666


In [272]:
from sklearn import tree
from pylab import *

# decision tree classifier
classifier = tree.DecisionTreeClassifier(max_depth=5)
classifier.fit(Xtr, Ytr)
s1 = classifier.predict(Xde)
s2 = classifier.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.7254901960784313
0.8019323671497585


In [276]:
from sklearn.svm import SVC
from pylab import *

# support vector machine
classifier = SVC(C = 100, kernel='poly', degree=2)#,gamma=200)
classifier.fit(Xtr, Ytr)
svc_class1 = classifier.predict(Xde)
svc_class2 = classifier.predict(Xte)
print(mean(svc_class1==Yde))
print(mean(svc_class2==Yte))

0.7254901960784313
0.7729468599033816


In [102]:
from sklearn.linear_model import Perceptron

# perceptron model
classifier = Perceptron(random_state=0, max_iter= 125)
classifier.fit(Xtr, Ytr)
percept_model = classifier.predict(Xde)
print(mean(percept_model==Yde))

0.7058823529411765


In [203]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=2, weights='uniform').fit(Xtr, Ytr)
s1 = clf.predict(Xde)
s2 = clf.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.6470588235294118
0.821256038647343


In [269]:
from sklearn.ensemble import RandomForestClassifier
rand_forest = RandomForestClassifier(n_estimators=1000,max_features=50, max_depth=13, random_state=22, criterion='gini').fit(Xtr,Ytr)
s1 = rand_forest.predict(Xde)
s2 = rand_forest.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.6862745098039216
0.8115942028985508


In [260]:
from sklearn.neural_network import MLPClassifier
#neural network

clf = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(7, 2), random_state=2).fit(Xtr,Ytr)
s1 = clf.predict(Xde)
s2 = clf.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.7254901960784313
0.8260869565217391


In [182]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(Xtr, Ytr)
s1 = clf.predict(Xde)
s2 = clf.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.7254901960784313
0.8260869565217391


In [279]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(C=.4, random_state=12, multi_class='ovr', max_iter=200).fit(Xtr, Ytr)
s1 = clf.predict(Xde)
s2 = clf.predict(Xte)
print(mean(s1==Yde))
print(mean(s2==Yte))

0.6862745098039216
0.8164251207729468
